version: "3.2"
services:
  mc:
    container_name: YC-${ENV}
    depends_on:
      - mysql
    image: yukkuricraft/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      YC_ENV: ${ENV_TYPE}
      MOTD: ${ENV_TYPE}-${MC_TYPE}_${MC_VERSION}[${PAPER_BUILD}]
      EULA: 'true'
      VERSION: ${MC_VERSION}
      TYPE: ${MC_TYPE}
      PAPER_BUILD: ${PAPER_BUILD}
      STOP_SERVER_ANNOUNCE_DELAY: 5
      COPY_CONFIG_DEST: /data
      EXEC_DIRECTLY: 'true'
    ports:
      - ${HOST_PORT}:25565
    volumes:
      -
        type: bind
        source: ${MC_FS_ROOT}/prod/worlds # This should always mount prod
        target: /worlds
      - ycworlds:/yc-worlds
      - mcdata:/data # For now.
      - ./minecraft-data/plugins:/plugins
      - ./minecraft-data/config:/config
    networks:
      - ycnet
  mysql:
    container_name: MySQL-${ENV}
    image: mysql/mysql-server:5.7
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ycnet

volumes:
  mcdata:
  dbdata:
  ycworlds:

networks:
  ycnet:
