#
# Temp file? Generate eventually?
#

version: '3.4'
services:
  mysql:
    container_name: YC-Api
    image: yukkuricraft/yc-docker-api
    volumes:
    - ./src:/app/src
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 5000:5000
    - 5001:5001
