version: "3.2"
services:
  mc:
    container_name: YC-${ENV}
    image: yukkuricraft/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      EULA: 'true'
      VERSION: 1.16.5
      TYPE: PAPER
      PAPER_BUILD: ${PAPER_BUILD}
      STOP_SERVER_ANNOUNCE_DELAY: 5
      COPY_CONFIG_DEST: /data
      EXEC_DIRECTLY: 'true'
    ports:
      - ${HOST_PORT}:25565
    volumes:
      -
        type: bind
        source: ${MC_FS_ROOT}/${ENV}/worlds
        target: /yc-worlds
      - prodmcdata:/data # For now.
      - ./minecraft-data/plugins:/plugins
      - ./minecraft-data/config:/config
  mysql:
    container_name: MySQL-${ENV}
    image: mysql/mysql-server:5.7
    volumes:
      - proddbdata:/var/lib/mysql

volumes:
  prodmcdata:
  proddbdata:
