#
# Temp file? Generate eventually?
#

version: '3.4'
services:
  mysql:
    container_name: YC-Api
    image: yukkuricraft/yc-docker-api
    restart: 'on-failure'
    volumes:
    - /usr/bin/docker:/usr/bin/docker
    - /usr/bin/docker-compose:/usr/bin/docker-compose
    - /var/run/docker.sock:/var/run/docker.sock
    - ./:/app
    ports:
    - 5000:5000
    - 5001:5001
