#!/usr/bin/env python3

import os
import sys
from pathlib import Path

sys.path.append(Path(__file__).parent.as_posix())

from src.generator.generator import GeneratorType, get_generator

if __name__ == "__main__":
    env_str = os.getenv("ENV")
    if env_str is None:
        raise Exception("Environment variable 'ENV' was not set. Must be set to generate docker-compose file. Use Makefile targets ('make generate') instead of invoking manually.")
    else:
        gen = get_generator(GeneratorType.DOCKER_COMPOSE, Env(env_str))
        gen.run()

