#!/usr/bin/env python3

import os
import sys
from pathlib import Path

sys.path.append(Path(__file__).parent.as_posix())

from src.generator.generator import GeneratorType, get_generator

if __name__ == "__main__":
    base_env = os.getenv("BASE_ENV")
    new_env = os.getenv("NEW_ENV")
    if base_env is None:
        raise Exception("Environment variable 'BASE_ENV' was not set. Must be set to know what env to copy configs from.\n    Use Makefile targets ('make create_new_env') instead of invoking manually.")
    elif new_env is None:
        raise Exception("Environment variable 'NEW_ENV' was not set. Must be set to know what env we're creating.\n    Use Makefile targets ('make create_new_env') instead of invoking manually.")
    else:

        gen = get_generator(GeneratorType.NEW_DEV_ENV, base_env)
        gen.run(new_env)

