# This config is used to dynamically generated a docker-compose.yml from the docker-compose.tpl.yml.
# This is because repeating the minecraft server container definition 7+ times is gross when
#   all that changes between configs is the name of the world group.
#
# This also effectively acts as a way to "enable" and "disable" world groups.

world_groups:
    - survival
    - creative
    - old-gensokyo
    - neo-gensokyo
    - lobby
    - minigames-and-events
