# Human readable name for this environment.
# Machine env name is defined by the folder name. ie, `minecraft-data/<env_name>/config.yml`
human-env-name: 'Development 1'

# Defines which environment's files we copy, or treat as our "base"
copy-source-env: prod

# Any plugin that's ignored will simply never get copied when spinning up the dev environment.
copy-ignored-plugins:
  - DiscordSRV # If re-enabling, MAKE SURE to modify configs to not use prod/real discord server
  - dynmap # If re-enabling, this will take extra time due to copying large numbers of files.
