# This is the template docker-compose config that will generate the actual config used to run.
# We do this because copypasting this seven times is gross when everything is the same minus worldgroup name.
#
# We also get the benefit of being able to effectively "enable" and "disable" world groups due to the dynamic nature.
#
# Variable Interpolations:
# - We have two layers of interpolations in this file.
#   - One is Docker's env var subs. These are denoted by the ${} syntax. These substitute values from the running context's env vars.
#   - The second is our own value injection system. We programatically inject our values in the BaseGenerator class. These use the <<var>> syntax.
#
#


version: "3.4"

# These custom_extensions are read by docker_compose_gen.py and used as templates for generating
# the full service definition.
custom_extensions:
  mc_service_template: # Config used to run all world group containers.
    image: yukkuricraft/minecraft-server
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

    # Healthchecks are done by default in the itzg/minecraft-server image
    # https://docker-minecraft-server.readthedocs.io/en/latest/misc/healthcheck/

    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - ycnet
    environment:
      YC_ENV: ${ENV_TYPE}
      MOTD: "<<WORLDGROUP>>-${ENV_TYPE}-${MC_TYPE}_${MC_VERSION}[${PAPER_BUILD}]"
      DEBUG: "true"
      EULA: "true"
      COPY_PROD_WORLD: ${COPY_PROD_WORLD}
      COPY_PROD_PLUGINS: ${COPY_PROD_PLUGINS}
      VERSION: ${MC_VERSION}
      TYPE: ${MC_TYPE}
      PAPER_BUILD: ${PAPER_BUILD}
      STOP_SERVER_ANNOUNCE_DELAY: 5
      COPY_CONFIG_DEST: /data
      EXEC_DIRECTLY: "true"
      UID: ${UID}
      GID: ${GID}
      RCON_PASSWORD_FILE: /rcon.password
    labels:
      net.yukkuricraft.env: ${ENV}
      net.yukkuricraft.container_type: minecraft
    volumes:
      - type: bind
        source: ${MC_FS_ROOT}/env/prod/<<WORLDGROUP>>/worlds # This should always mount prod
        target: /worlds-bindmount-prod
        read_only: ${BINDMOUNT_RO}
        bind:
          create_host_path: true
      - type: bind
        source: ${MC_FS_ROOT}/env/prod/<<WORLDGROUP>>/plugins # This should always mount prod
        target: /plugins-bindmount-prod
        read_only: ${BINDMOUNT_RO}
        bind:
          create_host_path: true
      - mcdata_<<WORLDGROUP>>:/data
      - ${YC_REPO_ROOT}/secrets/rcon.password:/rcon.password
      - ${YC_REPO_ROOT}/secrets/configs/${ENV}/worlds/default:/yc-default-configs
      - ${YC_REPO_ROOT}/secrets/configs/${ENV}/worlds/<<WORLDGROUP>>/plugins:/yc-plugin-configs
      - ${YC_REPO_ROOT}/secrets/configs/${ENV}/worlds/<<WORLDGROUP>>/server:/yc-server-configs
      - ${MC_FS_ROOT}/logs/${ENV}/worlds/<<WORLDGROUP>>/:/data/logs
      - ycworldsvolume_<<WORLDGROUP>>:/worlds-volume-dev # This volume is unused in prod. Only in dev.
      - ycpluginsvolume_<<WORLDGROUP>>:/plugins-volume-dev # Also unused in prod

  mc_backups_sidecar_template:
    image: yukkuricraft/mc-backup-restic
    environment:
      BACKUP_NAME: <<WORLDGROUP>>
      BACKUP_INTERVAL: "3h"
      BACKUP_METHOD: restic
      SRC_DIR: /worlds-bindmount-prod
      RCON_HOST: set-by-generator
      RCON_PASSWORD_FILE: /rcon.password
      RESTIC_REPOSITORY: /backups
      RESTIC_PASSWORD_FILE: /restic.password
      PRUNE_RESTIC_RETENTION: --keep-last 16 --keep-daily 14 --keep-weekly 8 --keep-monthly 24 --keep-yearly 666
      PAUSE_IF_NO_PLAYERS: false
      ENTRYPOINT_TARGET: /usr/bin/backup loop
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
    depends_on: {}
    networks:
      - ycnet
    labels:
      net.yukkuricraft.env: ${ENV}
      net.yukkuricraft.container_type: backup
    volumes:
      - ${YC_REPO_ROOT}/secrets/restic.password:/restic.password
      - ${YC_REPO_ROOT}/secrets/rcon.password:/rcon.password
      - ${BACKUPS_ROOT}/restic-<<WORLDGROUP>>:/backups
    volumes_from:
      - mc_<<WORLDGROUP>>:ro

  velocity_template:
    depends_on: {}
    image: itzg/bungeecord
    environment:
      DEBUG: "false"
      TYPE: "VELOCITY"
      SYNC_SKIP_NEWER_IN_DESTINATION: "false"
    labels:
      net.yukkuricraft.env: ${ENV}
      net.yukkuricraft.container_type: velocity
      net.yukkuricraft.container_name: velocity
    volumes:
      - velocity-${ENV}:/server
      - ${YC_REPO_ROOT}/gen/velocity-${ENV}.toml:/config/velocity.toml
      - ${YC_REPO_ROOT}/secrets/velocity/forwarding.secret:/config/forwarding.secret
    ports:
      - "${VELOCITY_PORT}:25577"
    networks:
      - ycnet

# "Static" services
services:
  mysql:
    container_name: YC-${ENV}-mysql
    image: mysql:5.7
    env_file:
      - ./secrets/db.env
    volumes:
      - dbdata:/var/lib/mysql
    labels:
      net.yukkuricraft.env: ${ENV}
      net.yukkuricraft.container_type: mysql
      net.yukkuricraft.container_name: mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 10s
      timeout: 10s
      retries: 15
    networks:
      - ycnet

  mysql_backup:
    image: yukkuricraft/mysql-backup-restic
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./secrets/mysql_backup_restic_config
    labels:
      net.yukkuricraft.env: ${ENV}
      net.yukkuricraft.container_type: backup
      net.yukkuricraft.container_name: mysql_backup
    environment:
      DB_SERVER: YC-${ENV}-mysql
      DB_USER: root
      DB_PORT: 3306
      DB_DUMP_TARGET: /mysqldump
      SRC_DIR: /mysqldump
      DEST_DIR: /backups
      RESTIC_HOSTNAME: YC-${ENV}-mysql_backup
      PRUNE_BACKUPS_DAYS: 7
      RESTIC_REPOSITORY: /backups
      RESTIC_PASSWORD_FILE: /restic.password
      PRUNE_RESTIC_RETENTION: --keep-last 8 --keep-daily 7 --keep-weekly 8 --keep-monthly 24 --keep-yearly 666
      MYSQLDUMP_OPTS: --quick --single-transaction
      ENTRYPOINT_TARGET: /entrypoint
      DB_DUMP_FREQ: 360 # Minutes
    volumes:
      - /mysqldump
      - ${YC_REPO_ROOT}/secrets/restic.password:/restic.password
      - ${BACKUPS_ROOT}/restic-mysql:/backups
    networks:
      - ycnet

  redis:
    image: redis:7.2-rc2
    volumes:
      - redisdata:/data
    labels:
      net.yukkuricraft.env: ${ENV}
      net.yukkuricraft.container_type: redis 
      net.yukkuricraft.container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 15
    networks:
      - ycnet

# Volumes will also be dynamically generated for each "enabled" world group.
volumes:
  dbdata:
  redisdata:

# Networks will be automatically generated as ycnet-${ENV}
networks:
  ycnet:
