# This TOML file is used to configure a given environment.
# It contains both general settings for our dynamically generated app configs
#     as well as runtime env vars for our individual containers

[general]
description="""
It's not actually prod.

But what if it is.

aaaa
"""

[world-groups]
# World groups represent each group of thematically-linked worlds. In effect, this corresponds to the number of minecraft servers we have running.
# The values in the world-groups.enabled_groups array will be used to generate all dynamic configs.

# In other words, modify this list to configure how many worldgroups you want.
# Values must be alphanumeric or underscore. (NO HYPHENS)
enabled_groups = [
    "lobby",
    "projectgo",
    "survival",
    "creative",
]

[runtime-environment-variables]
# These environment variables are generated as gen/{env}.env which are used as args to --env-file in docker-compose commands.
# We also dynamically generate certain environment variables:
# - 'ENV': This var is dynamically added based on the TOML config's filename. 'prod.toml` will generate 'ENV=prod', etc.

# If empty or not set, any use of the alias will default to the true env name.
ENV_ALIAS = "YC"
MC_FS_ROOT = "/var/lib/yukkuricraft"
MC_TYPE = "PAPER"
MC_VERSION = "1.19.1"
PAPER_BUILD = 318
BINDMOUNT_RO = false

VELOCITY_PORT = 25605

YC_REPO_ROOT = "/home/remi/development/Yukkuricraft"
